sudo: false
language: ruby
rvm:
  - 2.1.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
  - gem install jekyll
  - gem install RedCloth
  - gem install i18n
  - gem install json
script:
  - jekyll build
