# Dependencies
markdown:         kramdown
highlighter:      pygments
gems:
  - jemoji

# Permalinks
permalink:        pretty

# Setup
title:            David Ernst
tagline:          'A personal site'
description:      'David Ernst — A personal site'
url:              http://dsernst.com
baseurl:          '/'
paginate:         5

author:
  name:           'David Ernst'
  url:            https://twitter.com/dsernst
  email:          hello@dsernst.com

# Custom vars
github:
  repo:           https://github.com/dsernst/dsernst.github.io

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      author:
        name: "David Ernst"
