# Dependencies
markdown:         kramdown
pygments:         true
gems:
  - jemoji

# Permalinks
permalink:        pretty

# Setup
title:            David Ernst
tagline:          'Because everybody should have a place to write.'
description:      'A personal site'
url:              http://dsernst.com
baseurl:          '/'
paginate:         5

author:
  name:           'David Ernst'
  url:            https://twitter.com/dsernst

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dsernst/dsernst.github.io
